apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: 'default'
  source:
    helm:
      parameters:
      - name: "argocd.giropopsSenhas.enabled"
        value: "true"
      - name: "argocd.randomLogger.enabled"
        value: "true"
    repoURL: 'https://github.com/willbossle/descomplicando-gitops-no-kubernetes-argocd.git'
    targetRevision: feat/day2
    path: app-of-apps
  destination:
    namespace: giropops-senhas
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
