apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-monitoring
  namespace: argocd
spec:
  project: 'default'
  source:
    repoURL: 'https://github.com/willbossle/descomplicando-gitops-no-kubernetes-argocd.git'
    targetRevision: feat/day2
    path: app-of-apps-monitoring
    helm:
      parameters:
      - name: "argocd.prometheus.enabled"
        value: "true"
      - name: "argocd.prometheus.ingress"
        value: "prometheus.company123.com"
      - name: "argocd.prometheus.enabled"
        value: "true"
      - name: "argocd.grafana.ingress"
        value: "prometheus.company123.com"
  destination:
    namespace: giropops-senhas
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
