apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
    - git:
        repoURL: 'https://github.com/willbossle/descomplicando-gitops-no-kubernetes-argocd.git'
        revision: feat/day3
        directories:
        - path: applicationset/apps/*/helm
          #   - path: applicationset/apps/random-logger/helm
          #     exclude: true
    - git:
        repoURL: 'https://github.com/willbossle/descomplicando-gitops-no-kubernetes-argocd.git'
        revision: feat/day3
        pathParamPrefix: cfg
        files:
        - path: applicationset/configs/dev.json
  template:
    metadata:
      name: '{{index .path.segments 2}}-{{.cluster.nome}}' #pega o terceiro nome do caminho completo (ex: applicationset(0)/apps(1)/giropops-senhas(2) e/ou random-logger(2))
    spec:
      project: "default"
      source:
        repoURL: 'https://github.com/willbossle/descomplicando-gitops-no-kubernetes-argocd.git'
        targetRevision: feat/day3
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
